### PR TITLE
Support booting from 2Gb MX35LF2GE4AD NAND Flash

### PR DESCRIPTION
**Pull request by ftyghome**
Hey:) After getting an Allwinner Nezha D1-H board, I found the SPL is unable to find TOC file and the NAND does not initialized properly. The problem seems to have something to do with the lack of configuration of its MX35LF2GE4AD SPI NAND Flash. In the boot0_head.c, I made some changes to the storage_data array, filled in information about the NAND according to the D1_Linux_SPI-NAND developer guide published by Allwinner.
image

Before the change, the SPL failed to get information about the NAND(like sector count per page, page count per block...) and consequently, it failed on finding where the TOC file locates.

image

Now the NAND in Nezha board works fine!

image

### CODE REVIEW

**Comment by ftyghome** [comment]
As a side note, I found that I don't need to change the storage_gpio configuration to make the SPI NAND Flash work 😄

**Comment by smaeul** [comment]
Thanks! I'm glad you got this working; it will be useful for other Nezha users as well.

Please sign off your changes (per [U-Boot](http://www.denx.de/wiki/view/U-Boot/Patches#Attributing_Code_Copyrights_Sign)/[Linux](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin) policy), and I will be happy to merge this.

**Comment by ftyghome** [comment]
Improved the description of commit and signed off :) Thank you!

**Comment by smaeul** [comment]
Merged this as 0ad88bfdb723b1ac74cca96122918f885a4781ac.

**Pull request closed without merging**
